USE QUAN_LY_THU_VIEN
GO

EXEC sp_MSforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all"
EXEC sp_MSforeachtable "DELETE FROM ?"
EXEC sp_MSforeachtable "ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all"
GO

SET IDENTITY_INSERT TAI_KHOAN ON;
INSERT INTO TAI_KHOAN (IDTaiKhoan, TenTK, HashMK, SDT, HoTen, GioiTinh, Email) VALUES
(1, 'admin',   'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', '0901234567', N'Nguyễn Quản Trị',  1, 'admin@huit.edu.vn'),
(2, 'staff01', 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', '0907654321', N'Trần Thị Thủ Thư',  0, 'thuthu@huit.edu.vn'),
(3, 'user01',  'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', '0988888888', N'Lê Văn Độc Giả',    1, 'user01@gmail.com');
SET IDENTITY_INSERT TAI_KHOAN OFF;

SET IDENTITY_INSERT THU_THU ON;
INSERT INTO THU_THU (IDThuThu, IDTaiKhoan) VALUES (1, 1), (2, 2);
SET IDENTITY_INSERT THU_THU OFF;

SET IDENTITY_INSERT DOC_GIA ON;
INSERT INTO DOC_GIA (IDDocGia, IDTaiKhoan, SoTienDatCoc) VALUES (1, 3, 100000);
SET IDENTITY_INSERT DOC_GIA OFF;

SET IDENTITY_INSERT THE_MUON ON;
INSERT INTO THE_MUON (IDTheMuon, IDDocGia, NgayCap, NgayHetHan, MaKichHoat, TrangThai)
VALUES (1, 1, GETDATE(), DATEADD(YEAR, 1, GETDATE()), 123456, 1);
SET IDENTITY_INSERT THE_MUON OFF;
GO

SET IDENTITY_INSERT NHA_PHAT_HANH ON;
INSERT INTO NHA_PHAT_HANH (IDNhaPhatHanh, TenNhaPhatHanh) VALUES
(1, N'NXB Trẻ'), (2, N'NXB Giáo Dục'), (3, N'Kim Đồng'), (4, N'Nhã Nam'), (5, N'NXB Tổng Hợp TP.HCM');
SET IDENTITY_INSERT NHA_PHAT_HANH OFF;

SET IDENTITY_INSERT TAC_GIA ON;
INSERT INTO TAC_GIA (IDTacGia, TenTG) VALUES
(1, N'Ngô Tất Tố'), (2, N'Tô Hoài'), (3, N'J.K. Rowling'), (4, N'Nguyễn Nhật Ánh'), (5, N'Dan Brown'), (6, N'Haruki Murakami');
SET IDENTITY_INSERT TAC_GIA OFF;
GO

SET IDENTITY_INSERT SACH ON;
INSERT INTO SACH (IDSach, TenSach, IDNhaPhatHanh, IDNguoiThem) VALUES
(1, N'Dế Mèn Phiêu Lưu Ký', 3, 1),
(2, N'Tắt Đèn',             2, 1),
(3, N'Harry Potter và Hòn Đá Phù Thủy', 1, 1),
(4, N'Cho Tôi Xin Một Vé Đi Tuổi Thơ',  1, 2),
(5, N'Mắt Biếc',            1, 2),
(6, N'Mật Mã Da Vinci',     4, 1),
(7, N'Rừng Na Uy',          4, 2);
SET IDENTITY_INSERT SACH OFF;

SET IDENTITY_INSERT CHI_TIET_TAC_GIA ON;
INSERT INTO CHI_TIET_TAC_GIA (IDChiTiet, IDSach, IDTacGia) VALUES
(1, 1, 2), (2, 2, 1), (3, 3, 3), (4, 4, 4), (5, 5, 4), (6, 6, 5), (7, 7, 6);
SET IDENTITY_INSERT CHI_TIET_TAC_GIA OFF;

SET IDENTITY_INSERT BAN_SAO_SACH ON;
INSERT INTO BAN_SAO_SACH (IDBanSao, IDSach, IDNguoiNhap, GiaNhap, TrangThai) VALUES
(1, 1, 1, 45000,  1), 
(2, 1, 1, 45000,  1), 
(3, 2, 1, 35000,  1), 
(4, 3, 1, 120000, 0), 
(5, 4, 2, 75000,  1),
(6, 4, 2, 75000,  0),
(7, 5, 2, 80000,  1),
(8, 5, 2, 80000,  1),
(9, 6, 1, 150000, 0),
(10, 7, 2, 95000,  1);
SET IDENTITY_INSERT BAN_SAO_SACH OFF;
GO

SET IDENTITY_INSERT PHIEU_MUON ON;
INSERT INTO PHIEU_MUON (IDPhieuMuon, IDDocGia, NgayDangKi, HanTra, TrangThai, TienCoc) VALUES
(1, 1, DATEADD(DAY, -20, GETDATE()), DATEADD(DAY, 10, GETDATE()), 1, 50000.00),
(2, 1, DATEADD(DAY, -5, GETDATE()), DATEADD(DAY, 25, GETDATE()), 1, 100000.00),
(3, 1, DATEADD(DAY, -2, GETDATE()), DATEADD(DAY, 28, GETDATE()), 1, 50000.00);
SET IDENTITY_INSERT PHIEU_MUON OFF;

SET IDENTITY_INSERT CHI_TIET_PHIEU_MUON ON;
INSERT INTO CHI_TIET_PHIEU_MUON (IDChiTiet, IDPhieuMuon, IDBanSao, TrangThai, NgayMuon, NgayTra, TienPhat, LiDo) VALUES
(1, 1, 1, 1, DATEADD(DAY, -20, GETDATE()), DATEADD(DAY, -15, GETDATE()), 0, NULL),
(2, 1, 3, 1, DATEADD(DAY, -20, GETDATE()), DATEADD(DAY, -12, GETDATE()), 0, NULL),
(3, 2, 5, 1, DATEADD(DAY, -5, GETDATE()), NULL, 0, NULL),
(4, 2, 6, 1, DATEADD(DAY, -5, GETDATE()), NULL, 0, NULL),
(5, 3, 9, 1, DATEADD(DAY, -2, GETDATE()), NULL, 0, NULL);
SET IDENTITY_INSERT CHI_TIET_PHIEU_MUON OFF;
GO

DBCC CHECKIDENT ('TAI_KHOAN', RESEED, 3);
DBCC CHECKIDENT ('THU_THU', RESEED, 2);
DBCC CHECKIDENT ('DOC_GIA', RESEED, 1);
DBCC CHECKIDENT ('THE_MUON', RESEED, 1);
DBCC CHECKIDENT ('NHA_PHAT_HANH', RESEED, 5);
DBCC CHECKIDENT ('TAC_GIA', RESEED, 6);
DBCC CHECKIDENT ('SACH', RESEED, 7);
DBCC CHECKIDENT ('CHI_TIET_TAC_GIA', RESEED, 7);
DBCC CHECKIDENT ('BAN_SAO_SACH', RESEED, 10);
DBCC CHECKIDENT ('PHIEU_MUON', RESEED, 3);
DBCC CHECKIDENT ('CHI_TIET_PHIEU_MUON', RESEED, 5);
GO
