CREATE DATABASE QUAN_LY_THU_VIEN
GO

USE QUAN_LY_THU_VIEN
GO

CREATE TABLE TAI_KHOAN
(
    IDTaiKhoan INT IDENTITY(1,1),
    TenTK VARCHAR(50) NOT NULL,
    HashMK VARCHAR(100)NOT NULL,
    SDT VARCHAR(10)NOT NULL,
    HoTen NVARCHAR(100)NOT NULL,
    GioiTinh BIT NULL,
    Email VARCHAR(100)NOT NULL,

    CONSTRAINT PK_TAIKHOAN PRIMARY KEY(IDTaiKhoan),
    CONSTRAINT U_TenTK UNIQUE(TenTK)
)

CREATE TABLE THU_THU
(
    IDThuThu INT IDENTITY(1,1),
    IDTaiKhoan INT,

    CONSTRAINT PK_THUTHU PRIMARY KEY(IDThuThu),
    CONSTRAINT FK_THUTHU_TAIKHOAN FOREIGN KEY(IDTaiKhoan) REFERENCES TAI_KHOAN(IDTaiKhoan)
)

CREATE TABLE DOC_GIA
(
    IDDocGia INT IDENTITY(1,1),
    IDTaiKhoan INT,
    SoTienDatCoc DECIMAL(18,2)NOT NULL DEFAULT 0,
    TrangThai BIT DEFAULT 1,

    CONSTRAINT PK_NGUOIMUON PRIMARY KEY(IDDocGia),
    CONSTRAINT FK_NGUOIMUON_TAIKHOAN FOREIGN KEY(IDTaiKhoan) REFERENCES TAI_KHOAN(IDTaiKhoan),

)

CREATE TABLE THE_MUON
(
    IDTheMuon INT IDENTITY(1,1),
    IDDocGia INT,
    NgayCap DATETIME NOT NULL DEFAULT GETDATE(),
    NgayHetHan DATETIME NOT NULL DEFAULT GETDATE(),
    MaKichHoat INT,
    TrangThai BIT DEFAULT 0,

    CONSTRAINT PK_THEMUON PRIMARY KEY(IDTheMuon),
    CONSTRAINT FK_THEMUON_DOCGIA FOREIGN KEY(IDDocGia) REFERENCES DOC_GIA(IDDocGia),
    CONSTRAINT U_MAKICHHOAT UNIQUE(MaKichHoat),

)



CREATE TABLE NHA_PHAT_HANH
(
    IDNhaPhatHanh INT IDENTITY(1,1),
    TenNhaPhatHanh NVARCHAR(50),

    CONSTRAINT PK_NHAPHATHANH PRIMARY KEY(IDNhaPhatHanh)
)

CREATE TABLE SACH
(
    IDSach INT IDENTITY(1,1),
    TenSach NVARCHAR(100) NOT NULL,
    IDNhaPhatHanh INT,
    IDNguoiThem INT,

    CONSTRAINT PK_SACH PRIMARY KEY(IDSach),
    CONSTRAINT FK_SACH_NHAPHATHANH FOREIGN KEY(IDNhaPhatHanh) REFERENCES NHA_PHAT_HANH(IDNhaPhatHanh),
    CONSTRAINT FK_SACH_TAIKHOAN FOREIGN KEY(IDNguoiThem) REFERENCES TAI_KHOAN(IDTaiKhoan)
)

CREATE TABLE BAN_SAO_SACH
(
    IDBanSao INT IDENTITY(1,1),
    IDSach INT,
    IDNguoiNhap INT,
    NgayNhap DATETIME DEFAULT GETDATE(),
    GiaNhap DECIMAL(18,2),
    TrangThai TINYINT DEFAULT 1,

    CONSTRAINT PK_BANSAO PRIMARY KEY(IDBanSao),
    CONSTRAINT FK_BANSAO_SACH FOREIGN KEY(IDSach) REFERENCES SACH(IDSach),
    CONSTRAINT FK_BANSAO_TAIKHOAN FOREIGN KEY(IDNguoiNhap) REFERENCES TAI_KHOAN(IDTaiKhoan),
    
)

CREATE TABLE PHIEU_MUON
(
    IDPhieuMuon INT IDENTITY(1,1),
    IDDocGia INT,
    NgayDangKi DATETIME,
    HanTra DATETIME,
    TrangThai INT DEFAULT 0,
    TienCoc DECIMAL(18,2) DEFAULT 0,

    CONSTRAINT PK_PHIEUMUON PRIMARY KEY(IDPhieuMuon),
    CONSTRAINT FK_PHIEUMUON_DOCGIA FOREIGN KEY(IDDocGia) REFERENCES DOC_GIA(IDDocGia)
)

CREATE TABLE CHI_TIET_PHIEU_MUON
(
    IDChiTiet INT IDENTITY(1,1),
    IDPhieuMuon INT,
    IDBanSao INT,
    TrangThai INT,
    NgayMuon DATETIME,
    NgayTra DATETIME,
    TienPhat DECIMAL(18,2),
    LiDo NVARCHAR(255),

    CONSTRAINT PK_CHITIETPHIEU PRIMARY KEY(IDChiTiet),
    CONSTRAINT FK_CHITIETPHIEU_PHIEUMUON FOREIGN KEY (IDPhieuMuon) REFERENCES PHIEU_MUON(IDPhieuMuon),
    CONSTRAINT FK_CHITIETPHIEU_BANSAO FOREIGN KEY(IDBanSao) REFERENCES BAN_SAO_SACH(IDBanSao)
)


CREATE TABLE TAC_GIA
(
    IDTacGia INT IDENTITY(1,1),
    TenTG NVARCHAR(50),
    
    CONSTRAINT PK_TACGIA PRIMARY KEY(IDTacGia)
)

CREATE TABLE CHI_TIET_TAC_GIA
(
    IDChiTiet INT IDENTITY(1,1),
    IDSach INT,
    IDTacGia INT,

    CONSTRAINT PK_CHITIET PRIMARY KEY(IDChiTiet),
    CONSTRAINT FK_CHITIET_SACH FOREIGN KEY(IDSach) REFERENCES SACH(IDSach),
    CONSTRAINT FK_CHITIET_TACGIA FOREIGN KEY(IDTacGia) REFERENCES TAC_GIA(IDTacGia)
)


DROP TABLE CHI_TIET_TAC_GIA;
DROP TABLE BAN_SAO_SACH;
DROP TABLE THE_MUON;


DROP TABLE THU_THU;
DROP TABLE DOC_GIA;


DROP TABLE SACH;
DROP TABLE TAC_GIA;
DROP TABLE NHA_PHAT_HANH;
DROP TABLE TAI_KHOAN;