CREATE DATABASE QUAN_LY_THU_VIEN
GO

USE QUAN_LY_THU_VIEN
GO

CREATE TABLE TAI_KHOAN
(
    IDTaiKhoan INT IDENTITY(1,1) PRIMARY KEY,
    TenTK VARCHAR(50) NOT NULL UNIQUE,
    HashMK VARCHAR(100)NOT NULL,
    SDT VARCHAR(10)NOT NULL UNIQUE,
    HoTen NVARCHAR(100)NOT NULL,
    GioiTinh BIT NULL,
    Email VARCHAR(100)NOT NULL UNIQUE

)

CREATE TABLE THU_THU
(
    IDThuThu INT IDENTITY(1,1) PRIMARY KEY,
    IDTaiKhoan INT  FOREIGN KEY REFERENCES TAI_KHOAN(IDTaiKhoan) UNIQUE,

)

CREATE TABLE DOC_GIA
(
    IDDocGia INT IDENTITY(1,1) PRIMARY KEY,
    IDTaiKhoan INT FOREIGN KEY REFERENCES TAI_KHOAN(IDTaiKhoan) UNIQUE,
    SoTienDatCoc DECIMAL(18,2)NOT NULL DEFAULT 0,
    TrangThai BIT DEFAULT 1,

)

CREATE TABLE THE_MUON
(
    IDTheMuon INT IDENTITY(1,1) PRIMARY KEY,
    IDDocGia INT FOREIGN KEY REFERENCES DOC_GIA(IDDocGia) UNIQUE,
    NgayCap DATE NOT NULL DEFAULT GETDATE(),
    NgayHetHan DATE NOT NULL DEFAULT GETDATE(),
    MaKichHoat INT UNIQUE,
    TrangThai BIT DEFAULT 0,
)

CREATE TABLE NHA_PHAT_HANH
(
    IDNhaPhatHanh INT IDENTITY(1,1) PRIMARY KEY,
    TenNhaPhatHanh NVARCHAR(50),
)

CREATE TABLE SACH
(
    IDSach INT IDENTITY(1,1) PRIMARY KEY,
    TenSach NVARCHAR(100) NOT NULL,
    IDNhaPhatHanh INT FOREIGN KEY REFERENCES NHA_PHAT_HANH(IDNhaPhatHanh),
    IDNguoiThem INT FOREIGN KEY REFERENCES THU_THU(IDThuThu),
)

CREATE TABLE BAN_SAO_SACH
(
    IDBanSao INT IDENTITY(1,1) PRIMARY KEY,
    IDSach INT FOREIGN KEY REFERENCES SACH(IDSach),
    IDNguoiNhap INT FOREIGN KEY REFERENCES THU_THU(IDThuThu),
    NgayNhap DATETIME DEFAULT GETDATE(),
    GiaNhap DECIMAL(18,2),
    TrangThai TINYINT DEFAULT 1,
)

CREATE TABLE PHIEU_MUON
(
    IDPhieuMuon INT IDENTITY(1,1) PRIMARY KEY,
    IDDocGia INT FOREIGN KEY REFERENCES DOC_GIA(IDDocGia),
    NgayDangKi DATETIME,
    HanTra DATETIME,
    TrangThai INT DEFAULT 0,
    TienCoc DECIMAL(18,2) DEFAULT 0
    
)

CREATE TABLE CHI_TIET_PHIEU_MUON
(
    IDChiTiet INT IDENTITY(1,1) PRIMARY KEY,
    IDPhieuMuon INT FOREIGN KEY REFERENCES PHIEU_MUON(IDPhieuMuon),
    IDBanSao INT FOREIGN KEY REFERENCES BAN_SAO_SACH(IDBanSao),
    TrangThai INT,
    NgayMuon DATETIME,
    NgayTra DATETIME,
    TienPhat DECIMAL(18,2),
    LiDo NVARCHAR(255),
)


CREATE TABLE TAC_GIA
(
    IDTacGia INT IDENTITY(1,1) PRIMARY KEY,
    TenTG NVARCHAR(50),
)

CREATE TABLE CHI_TIET_TAC_GIA
(
    IDChiTiet INT IDENTITY(1,1) PRIMARY KEY,
    IDSach INT FOREIGN KEY REFERENCES SACH(IDSach),
    IDTacGia INT FOREIGN KEY REFERENCES TAC_GIA(IDTacGia)
)


-- 1. Xóa các bảng chi tiết/bảng trung gian 
DROP TABLE IF EXISTS CHI_TIET_TAC_GIA;
DROP TABLE IF EXISTS CHI_TIET_PHIEU_MUON;

-- 2. Xóa các bảng tham chiếu trực tiếp đến bảng gốc 
DROP TABLE IF EXISTS BAN_SAO_SACH;
DROP TABLE IF EXISTS PHIEU_MUON;
DROP TABLE IF EXISTS THE_MUON;
DROP TABLE IF EXISTS SACH;

-- 3. Xóa các bảng vai trò người dùng 
DROP TABLE IF EXISTS THU_THU;
DROP TABLE IF EXISTS DOC_GIA;

-- 4. Cuối cùng mới xóa các bảng gốc/danh mục (Level 0)
DROP TABLE IF EXISTS TAC_GIA;
DROP TABLE IF EXISTS NHA_PHAT_HANH;
DROP TABLE IF EXISTS TAI_KHOAN;