//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_QuanLiThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAN_SAO_SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BAN_SAO_SACH()
        {
            this.CHI_TIET_PHIEU_MUON = new HashSet<CHI_TIET_PHIEU_MUON>();
        }
    
        public int IDBanSao { get; set; }
        public Nullable<int> IDSach { get; set; }
        public Nullable<int> IDNguoiNhap { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
        public Nullable<decimal> GiaNhap { get; set; }
        public Nullable<byte> TrangThai { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_PHIEU_MUON> CHI_TIET_PHIEU_MUON { get; set; }
    }
}
