//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_QuanLiThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_PHIEU_MUON
    {
        public int IDChiTiet { get; set; }
        public Nullable<int> IDPhieuMuon { get; set; }
        public Nullable<int> IDBanSao { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<decimal> TienPhat { get; set; }
        public string LiDo { get; set; }
    
        public virtual BAN_SAO_SACH BAN_SAO_SACH { get; set; }
        public virtual PHIEU_MUON PHIEU_MUON { get; set; }
    }
}
