//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_QuanLiThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHI_TIET_TAC_GIA
    {
        public int IDChiTiet { get; set; }
        public Nullable<int> IDSach { get; set; }
        public Nullable<int> IDTacGia { get; set; }
    
        public virtual SACH SACH { get; set; }
        public virtual TAC_GIA TAC_GIA { get; set; }
    }
}
