//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_QuanLiThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOC_GIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DOC_GIA()
        {
            this.PHIEU_MUON = new HashSet<PHIEU_MUON>();
            this.THE_MUON = new HashSet<THE_MUON>();
        }
    
        public int IDDocGia { get; set; }
        public Nullable<int> IDTaiKhoan { get; set; }
        public decimal SoTienDatCoc { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual TAI_KHOAN TAI_KHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEU_MUON> PHIEU_MUON { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THE_MUON> THE_MUON { get; set; }
    }
}
