//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_QuanLiThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEU_MUON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHIEU_MUON()
        {
            this.CHI_TIET_PHIEU_MUON = new HashSet<CHI_TIET_PHIEU_MUON>();
        }
    
        public int IDPhieuMuon { get; set; }
        public Nullable<int> IDDocGia { get; set; }
        public Nullable<System.DateTime> NgayDangKi { get; set; }
        public Nullable<System.DateTime> HanTra { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<decimal> TienCoc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_PHIEU_MUON> CHI_TIET_PHIEU_MUON { get; set; }
        public virtual DOC_GIA DOC_GIA { get; set; }
    }
}
