//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_QuanLiThuVien.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLThuVienEntities : DbContext
    {
        public QLThuVienEntities()
            : base("name=QLThuVienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAN_SAO_SACH> BAN_SAO_SACH { get; set; }
        public virtual DbSet<CHI_TIET_PHIEU_MUON> CHI_TIET_PHIEU_MUON { get; set; }
        public virtual DbSet<CHI_TIET_TAC_GIA> CHI_TIET_TAC_GIA { get; set; }
        public virtual DbSet<DOC_GIA> DOC_GIA { get; set; }
        public virtual DbSet<NHA_PHAT_HANH> NHA_PHAT_HANH { get; set; }
        public virtual DbSet<PHIEU_MUON> PHIEU_MUON { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
        public virtual DbSet<TAC_GIA> TAC_GIA { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public virtual DbSet<THE_MUON> THE_MUON { get; set; }
        public virtual DbSet<THU_THU> THU_THU { get; set; }
    }
}
