//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_QuanLiThuVien.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QUAN_LY_THU_VIENEntities : DbContext
    {
        public QUAN_LY_THU_VIENEntities()
            : base("name=QUAN_LY_THU_VIENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAN_SAO_SACH> BAN_SAO_SACH { get; set; }
        public virtual DbSet<CHI_TIET_PHIEU_MUON> CHI_TIET_PHIEU_MUON { get; set; }
        public virtual DbSet<CHI_TIET_TAC_GIA> CHI_TIET_TAC_GIA { get; set; }
        public virtual DbSet<DOC_GIA> DOC_GIA { get; set; }
        public virtual DbSet<NHA_PHAT_HANH> NHA_PHAT_HANH { get; set; }
        public virtual DbSet<PHIEU_MUON> PHIEU_MUON { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
        public virtual DbSet<TAC_GIA> TAC_GIA { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public virtual DbSet<THE_MUON> THE_MUON { get; set; }
        public virtual DbSet<THU_THU> THU_THU { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_DangKi(string fullName, string userName, string phoneNumber, string email, Nullable<bool> gender, string hashPass, Nullable<bool> role)
        {
            var fullNameParameter = fullName != null ?
                new ObjectParameter("fullName", fullName) :
                new ObjectParameter("fullName", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(bool));
    
            var hashPassParameter = hashPass != null ?
                new ObjectParameter("hashPass", hashPass) :
                new ObjectParameter("hashPass", typeof(string));
    
            var roleParameter = role.HasValue ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_DangKi", fullNameParameter, userNameParameter, phoneNumberParameter, emailParameter, genderParameter, hashPassParameter, roleParameter);
        }
    
        public virtual ObjectResult<sp_DangNhap_Result> sp_DangNhap(string userName, string hashPass)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var hashPassParameter = hashPass != null ?
                new ObjectParameter("hashPass", hashPass) :
                new ObjectParameter("hashPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DangNhap_Result>("sp_DangNhap", userNameParameter, hashPassParameter);
        }
    
        public virtual ObjectResult<sp_BaoCaoThongKe_Result> sp_BaoCaoThongKe(Nullable<System.DateTime> tuNgay, Nullable<System.DateTime> denNgay)
        {
            var tuNgayParameter = tuNgay.HasValue ?
                new ObjectParameter("tuNgay", tuNgay) :
                new ObjectParameter("tuNgay", typeof(System.DateTime));
    
            var denNgayParameter = denNgay.HasValue ?
                new ObjectParameter("denNgay", denNgay) :
                new ObjectParameter("denNgay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BaoCaoThongKe_Result>("sp_BaoCaoThongKe", tuNgayParameter, denNgayParameter);
        }
    
        public virtual ObjectResult<sp_CapNhatTaiKhoan_Result> sp_CapNhatTaiKhoan(Nullable<int> idTaiKhoan, string hoTen, string sdt, string email, Nullable<bool> gioiTinh, string hashMKMoi)
        {
            var idTaiKhoanParameter = idTaiKhoan.HasValue ?
                new ObjectParameter("idTaiKhoan", idTaiKhoan) :
                new ObjectParameter("idTaiKhoan", typeof(int));
    
            var hoTenParameter = hoTen != null ?
                new ObjectParameter("hoTen", hoTen) :
                new ObjectParameter("hoTen", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("gioiTinh", gioiTinh) :
                new ObjectParameter("gioiTinh", typeof(bool));
    
            var hashMKMoiParameter = hashMKMoi != null ?
                new ObjectParameter("hashMKMoi", hashMKMoi) :
                new ObjectParameter("hashMKMoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CapNhatTaiKhoan_Result>("sp_CapNhatTaiKhoan", idTaiKhoanParameter, hoTenParameter, sdtParameter, emailParameter, gioiTinhParameter, hashMKMoiParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_DoiMatKhau(Nullable<int> idTaiKhoan, string hashMKCu, string hashMKMoi)
        {
            var idTaiKhoanParameter = idTaiKhoan.HasValue ?
                new ObjectParameter("idTaiKhoan", idTaiKhoan) :
                new ObjectParameter("idTaiKhoan", typeof(int));
    
            var hashMKCuParameter = hashMKCu != null ?
                new ObjectParameter("hashMKCu", hashMKCu) :
                new ObjectParameter("hashMKCu", typeof(string));
    
            var hashMKMoiParameter = hashMKMoi != null ?
                new ObjectParameter("hashMKMoi", hashMKMoi) :
                new ObjectParameter("hashMKMoi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_DoiMatKhau", idTaiKhoanParameter, hashMKCuParameter, hashMKMoiParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_KhoaTaiKhoan(Nullable<int> idDocGia)
        {
            var idDocGiaParameter = idDocGia.HasValue ?
                new ObjectParameter("idDocGia", idDocGia) :
                new ObjectParameter("idDocGia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_KhoaTaiKhoan", idDocGiaParameter);
        }
    
        public virtual int sp_LayDanhSachSach(string keyword, string theLoai)
        {
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var theLoaiParameter = theLoai != null ?
                new ObjectParameter("theLoai", theLoai) :
                new ObjectParameter("theLoai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_LayDanhSachSach", keywordParameter, theLoaiParameter);
        }
    
        public virtual ObjectResult<sp_LayDanhSachTaiKhoan_Result> sp_LayDanhSachTaiKhoan(string keyword, Nullable<bool> trangThai, Nullable<bool> gioiTinh)
        {
            var keywordParameter = keyword != null ?
                new ObjectParameter("keyword", keyword) :
                new ObjectParameter("keyword", typeof(string));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("trangThai", trangThai) :
                new ObjectParameter("trangThai", typeof(bool));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("gioiTinh", gioiTinh) :
                new ObjectParameter("gioiTinh", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayDanhSachTaiKhoan_Result>("sp_LayDanhSachTaiKhoan", keywordParameter, trangThaiParameter, gioiTinhParameter);
        }
    
        public virtual ObjectResult<sp_LayPhieuMuon_Result> sp_LayPhieuMuon(Nullable<int> idDocGia, Nullable<int> trangThai)
        {
            var idDocGiaParameter = idDocGia.HasValue ?
                new ObjectParameter("idDocGia", idDocGia) :
                new ObjectParameter("idDocGia", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("trangThai", trangThai) :
                new ObjectParameter("trangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayPhieuMuon_Result>("sp_LayPhieuMuon", idDocGiaParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<sp_LaySachDocGia_Result> sp_LaySachDocGia(Nullable<int> idTaiKhoan)
        {
            var idTaiKhoanParameter = idTaiKhoan.HasValue ?
                new ObjectParameter("idTaiKhoan", idTaiKhoan) :
                new ObjectParameter("idTaiKhoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LaySachDocGia_Result>("sp_LaySachDocGia", idTaiKhoanParameter);
        }
    
        public virtual ObjectResult<sp_LayThongTinDocGia_Result> sp_LayThongTinDocGia(Nullable<int> idTaiKhoan)
        {
            var idTaiKhoanParameter = idTaiKhoan.HasValue ?
                new ObjectParameter("idTaiKhoan", idTaiKhoan) :
                new ObjectParameter("idTaiKhoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LayThongTinDocGia_Result>("sp_LayThongTinDocGia", idTaiKhoanParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_MoKhoaTaiKhoan(Nullable<int> idDocGia)
        {
            var idDocGiaParameter = idDocGia.HasValue ?
                new ObjectParameter("idDocGia", idDocGia) :
                new ObjectParameter("idDocGia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_MoKhoaTaiKhoan", idDocGiaParameter);
        }
    
        public virtual ObjectResult<sp_TaoPhieuMuon_Result> sp_TaoPhieuMuon(Nullable<int> idDocGia, Nullable<int> idBanSao, Nullable<System.DateTime> hanTra, Nullable<decimal> tienCoc, Nullable<int> idThuThu)
        {
            var idDocGiaParameter = idDocGia.HasValue ?
                new ObjectParameter("idDocGia", idDocGia) :
                new ObjectParameter("idDocGia", typeof(int));
    
            var idBanSaoParameter = idBanSao.HasValue ?
                new ObjectParameter("idBanSao", idBanSao) :
                new ObjectParameter("idBanSao", typeof(int));
    
            var hanTraParameter = hanTra.HasValue ?
                new ObjectParameter("hanTra", hanTra) :
                new ObjectParameter("hanTra", typeof(System.DateTime));
    
            var tienCocParameter = tienCoc.HasValue ?
                new ObjectParameter("tienCoc", tienCoc) :
                new ObjectParameter("tienCoc", typeof(decimal));
    
            var idThuThuParameter = idThuThu.HasValue ?
                new ObjectParameter("idThuThu", idThuThu) :
                new ObjectParameter("idThuThu", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TaoPhieuMuon_Result>("sp_TaoPhieuMuon", idDocGiaParameter, idBanSaoParameter, hanTraParameter, tienCocParameter, idThuThuParameter);
        }
    
        public virtual ObjectResult<sp_ThemSach_Result> sp_ThemSach(string tenSach, string theLoai, string isbn, Nullable<int> namXuatBan, Nullable<int> idNhaPhatHanh, string tenTacGia, Nullable<decimal> giaNhap, Nullable<int> idNguoiThem)
        {
            var tenSachParameter = tenSach != null ?
                new ObjectParameter("tenSach", tenSach) :
                new ObjectParameter("tenSach", typeof(string));
    
            var theLoaiParameter = theLoai != null ?
                new ObjectParameter("theLoai", theLoai) :
                new ObjectParameter("theLoai", typeof(string));
    
            var isbnParameter = isbn != null ?
                new ObjectParameter("isbn", isbn) :
                new ObjectParameter("isbn", typeof(string));
    
            var namXuatBanParameter = namXuatBan.HasValue ?
                new ObjectParameter("namXuatBan", namXuatBan) :
                new ObjectParameter("namXuatBan", typeof(int));
    
            var idNhaPhatHanhParameter = idNhaPhatHanh.HasValue ?
                new ObjectParameter("idNhaPhatHanh", idNhaPhatHanh) :
                new ObjectParameter("idNhaPhatHanh", typeof(int));
    
            var tenTacGiaParameter = tenTacGia != null ?
                new ObjectParameter("tenTacGia", tenTacGia) :
                new ObjectParameter("tenTacGia", typeof(string));
    
            var giaNhapParameter = giaNhap.HasValue ?
                new ObjectParameter("giaNhap", giaNhap) :
                new ObjectParameter("giaNhap", typeof(decimal));
    
            var idNguoiThemParameter = idNguoiThem.HasValue ?
                new ObjectParameter("idNguoiThem", idNguoiThem) :
                new ObjectParameter("idNguoiThem", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ThemSach_Result>("sp_ThemSach", tenSachParameter, theLoaiParameter, isbnParameter, namXuatBanParameter, idNhaPhatHanhParameter, tenTacGiaParameter, giaNhapParameter, idNguoiThemParameter);
        }
    
        public virtual ObjectResult<sp_TraSach_Result> sp_TraSach(Nullable<int> idChiTiet, Nullable<decimal> mucPhatNgay)
        {
            var idChiTietParameter = idChiTiet.HasValue ?
                new ObjectParameter("idChiTiet", idChiTiet) :
                new ObjectParameter("idChiTiet", typeof(int));
    
            var mucPhatNgayParameter = mucPhatNgay.HasValue ?
                new ObjectParameter("mucPhatNgay", mucPhatNgay) :
                new ObjectParameter("mucPhatNgay", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TraSach_Result>("sp_TraSach", idChiTietParameter, mucPhatNgayParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_XoaSach(Nullable<int> idSach)
        {
            var idSachParameter = idSach.HasValue ?
                new ObjectParameter("idSach", idSach) :
                new ObjectParameter("idSach", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_XoaSach", idSachParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_XoaTaiKhoan(Nullable<int> idTaiKhoan)
        {
            var idTaiKhoanParameter = idTaiKhoan.HasValue ?
                new ObjectParameter("idTaiKhoan", idTaiKhoan) :
                new ObjectParameter("idTaiKhoan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_XoaTaiKhoan", idTaiKhoanParameter);
        }
    }
}
