//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_QuanLiThuVien.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QUAN_LY_THU_VIENEntities : DbContext
    {
        public QUAN_LY_THU_VIENEntities()
            : base("name=QUAN_LY_THU_VIENEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAN_SAO_SACH> BAN_SAO_SACH { get; set; }
        public virtual DbSet<CHI_TIET_PHIEU_MUON> CHI_TIET_PHIEU_MUON { get; set; }
        public virtual DbSet<CHI_TIET_TAC_GIA> CHI_TIET_TAC_GIA { get; set; }
        public virtual DbSet<DOC_GIA> DOC_GIA { get; set; }
        public virtual DbSet<NHA_PHAT_HANH> NHA_PHAT_HANH { get; set; }
        public virtual DbSet<PHIEU_MUON> PHIEU_MUON { get; set; }
        public virtual DbSet<SACH> SACHes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TAC_GIA> TAC_GIA { get; set; }
        public virtual DbSet<TAI_KHOAN> TAI_KHOAN { get; set; }
        public virtual DbSet<THE_MUON> THE_MUON { get; set; }
        public virtual DbSet<THU_THU> THU_THU { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_DangKi(string fullName, string userName, string phoneNumber, string email, Nullable<bool> gender, string hashPass, Nullable<bool> role)
        {
            var fullNameParameter = fullName != null ?
                new ObjectParameter("fullName", fullName) :
                new ObjectParameter("fullName", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var phoneNumberParameter = phoneNumber != null ?
                new ObjectParameter("phoneNumber", phoneNumber) :
                new ObjectParameter("phoneNumber", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var genderParameter = gender.HasValue ?
                new ObjectParameter("gender", gender) :
                new ObjectParameter("gender", typeof(bool));
    
            var hashPassParameter = hashPass != null ?
                new ObjectParameter("hashPass", hashPass) :
                new ObjectParameter("hashPass", typeof(string));
    
            var roleParameter = role.HasValue ?
                new ObjectParameter("role", role) :
                new ObjectParameter("role", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_DangKi", fullNameParameter, userNameParameter, phoneNumberParameter, emailParameter, genderParameter, hashPassParameter, roleParameter);
        }
    
        public virtual ObjectResult<sp_DangNhap_Result> sp_DangNhap(string userName, string hashPass)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("userName", userName) :
                new ObjectParameter("userName", typeof(string));
    
            var hashPassParameter = hashPass != null ?
                new ObjectParameter("hashPass", hashPass) :
                new ObjectParameter("hashPass", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_DangNhap_Result>("sp_DangNhap", userNameParameter, hashPassParameter);
        }
    }
}
