//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_QuanLiThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SACH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SACH()
        {
            this.BAN_SAO_SACH = new HashSet<BAN_SAO_SACH>();
            this.CHI_TIET_TAC_GIA = new HashSet<CHI_TIET_TAC_GIA>();
        }
    
        public int IDSach { get; set; }
        public string TenSach { get; set; }
        public Nullable<int> IDNhaPhatHanh { get; set; }
        public Nullable<int> IDNguoiThem { get; set; }
        public string TheLoai { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> NamXuatBan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAN_SAO_SACH> BAN_SAO_SACH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHI_TIET_TAC_GIA> CHI_TIET_TAC_GIA { get; set; }
        public virtual NHA_PHAT_HANH NHA_PHAT_HANH { get; set; }
        public virtual THU_THU THU_THU { get; set; }
    }
}
