//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA_QuanLiThuVien.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THE_MUON
    {
        public int IDTheMuon { get; set; }
        public Nullable<int> IDDocGia { get; set; }
        public System.DateTime NgayCap { get; set; }
        public System.DateTime NgayHetHan { get; set; }
        public Nullable<int> MaKichHoat { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    
        public virtual DOC_GIA DOC_GIA { get; set; }
    }
}
